{% set version = "1.2" %} 
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hdtweedie
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/HDtweedie_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/HDtweedie/HDtweedie_{{ version }}.tar.gz
  sha256: f381a4421bc527de4786270843de57f6f82f96d8b029776d8836203b9d791d55

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('HDtweedie')"           # [not win]
    - "\"%R%\" -e \"library('HDtweedie')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=HDtweedie
  license: GPL-2.0-only
  summary: This package implements a iteratively reweighed least square (IRLS) strategy that incorporates a blockwise majorization decent (BMD) method, for efficiently computing the solution paths of the (grouped) lasso and the (grouped) elastic net for the Tweedie model.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy

# Package: HDtweedie
# Title: The Lasso for the Tweedie's Compound Poisson Model Using an IRLS-BMD Algorithm
# Version: 1.1
# Date: 2013-9-25
# Author: Wei Qian <weiqian@stat.umn.edu>, Yi Yang <yiyang@umn.edu>, Hui Zou <hzou@stat.umn.edu>
# Maintainer: Wei Qian <weiqian@stat.umn.edu>
# Description: This package implements a iteratively reweighed least square (IRLS) strategy that incorporates a blockwise majorization decent (BMD) method, for efficiently computing the solution paths of the (grouped) lasso and the (grouped) elastic net for the Tweedie model.
# License: GPL-2
# Packaged: 2013-10-22 00:55:04 UTC; weiqian
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2013-10-22 08:15:32
