travis:
  secure:
    BINSTAR_TOKEN: GtJdoo9ZE/Gy6ctt9IzXYmnI3wyFH9pQvCigd9GFR6IDnfjUqPUpBk2aOWNbr1zHzwsZb2nsfWrxqlk3SJS83KHJBaNO1VCWxqcrVgGw1EowCVZFYE5woXe+aXIW7Z2sQnxteqgmtQaRPm2to4hejM7IzaZkxI+lUQkTrp3+dOfwoUB5KD9PsvBakR2QN9qjx8ppbC40qBssAvJUvKuxg5vHwmS4xBwGVCpuRUCOBcpHNeEMu0Q3utBbJw1YPePIR3dWl8DzHGQCTbf7cn00CheH3fTiApBbY9zNCqyxiTe8n3Xrkznl0f7DibSULG3jN2y1xrHnICTce4fdR4xVcqOdXdcxFy1H5UXBIbK44mDB393Bnbvxex7g1VwxK92mvWVeCSaPF4NEtSknLOof4ZvltBgdMN2Vx3Q3Sh3cXiL4mkgL4P0ctkvD/DJ2rG95yHhc7sJpT3RUBPX2sAPqtuHcyz9czDjKEzL8F8YWfaCn4V/QHnbPVPlligdYAAeFuAUrL7NNC6evfWE7ckzEy74yabhdBPjcOBkykphxHCftxjJ0WqXfyFo1POrgN03V1P/0epr6Aq2frFXVoMhFOFbhl9LDCusup4RTCjsLr/URAiuBFR2/pbYyF5ekuGZzLk0tiWMkL/HyDT2f0HSUJSxzPR8TKmmpKF4pux9LTko=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
