appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: fdK+XRRfmS8yDIP8GMdJX7Er5cTR7LbdggK9TBy+fSQHc0AYuWBXJFgHXFNltlHzz8GRwyPND9puPtWvxqMEfR+D6Bo7qXKEVZwWedkYKkfv37FSgjU+J6Gsg/KSksa2/6vKembkLFT4DsW5+fLQmgtrpAq6N/ICRGyrkQ/h8FHnNTArBcM6xiNiM8uAdXsXirz+LKEd/EINrFbEtsmRPEVYdlvgLTmMQeXWyn5bctd5RifNyrZhbxbRjEVC/LvFulmWGG5nCBZ5rwRGzQ1sGadkLmXzV3PW7Hc8jdK/g7K7+QrhAx3FMb3dmdzcReRgwNhl8kiQwLktk98IeHk4i4nkdxjKrsrBv9Ehdk+lqQKkg1Rp/oOxKE8GAVkAfYsTkMt1BuYcRfsblPgGTHqi9p7lHBenA5jmAXhBM8ad82u/Ct2jkLiXbBKrAyHO+C8sKVPEzKODbFT/3mv69zjp6zW0XMRIZX46CKVks/L0Tq4de7hDH4D+cAkTZFwQw8mCW9u6GWje8F7Tq0ZGE3Fk1nBjVMgZYv3syV4CGpOs1FM7dF31WE5BNmXZOdX8FQh9efLXa/wjMGPF3JKhJwF7/HWu7ec6wRCtTiBdXbESvQoyLzHadhdnfJi58TFcYR5hQR1cJh/iQoXjmCe37+DcuXwZN0he73PLwjaqt+4L3LI=
conda_forge_output_validation: true
